### ISSUE TITLE
Provide verification from Drupal that it received data sent

### ISSUE THREAD

**Issue by shrop** [hb5co/drupal-ddp#13]
When any data is sent to Drupal, we need to track that Drupal confirms the data was received. If not, the data should be queued to be sent again.

**Comment by bfodeke** [comment]
Meteor is sending information back to Drupal as confirmation that data has been updates.  Drupal also sends confirmation as a response to the restws http_request.  If the request fails, the `updateNodeInDrupal` method returns `FALSE`
