### ISSUE TITLE
Simplify the node and user Drupal data objects

### ISSUE THREAD

**Issue by shrop** [hb5co/drupal-ddp#29]
@queso mentioned simplifying the Drupal related objects so they are friendlier for Meteor devs. Not sure if this is really possible and will at least be a lot of work to translate back to Drupal, but worth a conversation.

**Comment by bfodeke** [comment]
Currently, the restws module in Drupal is being used to help simplify the data going to Meteor.  @queso also helped by writing the registerType functionality to help break content types into collections in Meteor.  I think this is sufficient for now. Can reopen if there's need for even greater simplicity.
