### ISSUE TITLE
Create a server method to receive Drupal users

### ISSUE THREAD

**Issue by shrop** [hb5co/drupal-ddp#8]
Server method should receive user records and add them to the default Meteor users collection

**Comment by bfodeke** [comment]
This is mostly done. I'm still trying to figure out how to get the passwords that are set in Drupal to work in Meteor.  I'm already using the bcrypt module but I need to figure something out around the password salt in meteor

**Comment by shrop** [comment]
Sounds good @bfodeke. @queso relates to #12

**Comment by bfodeke** [comment]
Completed.
